### ISSUE TITLE
Error after Setup?

### ISSUE THREAD

**Issue by manule87** [lobaro/xentral-docker#1]
Hi, I am really happy to have found an Xentral Docker container but I have a problem after the installation.

I have set the file permissions for the folders and use a separate SQL container which creates the database.
The setup routine runs without errors but when I call the URL and want to log in to the system I get the following error message:

`Fatal error: Uncaught Error: Class 'Config' not found in /var/www/html/www/index.php:53 Stack trace: # 0 {main} thrown in /var/www/html/www/index.php on line 53`

I use the system behind a Jwilder reverse proxy with SSL
https://github.com/jwilder/nginx-proxy

Here is my Docker Compose File:
```
version: '3'

services:
  db:
    image: mariadb
    restart: always
    hostname: xentraldb
	container_name: xentraldb
    volumes:
      - /xentral/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret-rootpw
      - MYSQL_DATABASE=xentraldb
      - MYSQL_USER=xentraluser
      - MYSQL_PASSWORD=secret-userpw
    networks:
      - mynetwork

  xentral:
    image: lobaro/xentral-docker
    restart: always
    hostname: xentralcrm
    container_name: xentralcrm
    volumes:
      - /xentral/userdata:/var/www/html/userdata
      - /xentral/conf:/var/www/html/conf
      # Allows do run the update faster after recreating the container
      - /xentral/download:/var/www/html/download
      - /etc/localtime:/etc/localtime:ro
    links:
      - db:db
    environment:
      - VIRTUAL_HOST=xentral.domain.de
      - LETSENCRYPT_HOST=xentral.domain.de
      - LETSENCRYPT_EMAIL=xentral@domain.de
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
```

Can someone help?
